version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/integration"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/seed"
    schedule:
      interval: "weekly"
