version: "3.9"

services:
  service:
    image: ecommerce-user-service
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      logging/enabled: "true"
    container_name: ecommerce-user-service
    ports:
      - 1001:80
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_NAME=user
      - DB_USERNAME=sa
      - DB_PASSWORD=Password123
      - JWT_SECRET=DockerTestJWTFakeSecret
      - ASPNETCORE_ENVIRONMENT=Development
      - ELASTIC_APM_SERVER_URL=http://host.docker.internal:8200
      - ELASTIC_APM_SERVICE_NAME=user-service
      - ELASTIC_APM_EXIT_SPAN_MIN_DURATION=1us
      - ELASTIC_APM_CAPTURE_BODY=all
    depends_on:
      - db
    restart: on-failure

  db:
    container_name: ecommerce-user-service-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    restart: on-failure
