apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - sql-server-cred-secret.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - horizontal-pod-autoscaler.yml
  - sql-server.yml
