kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ecommerce-user-service-mssql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: managed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-user-service-mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-user-service-mssql
  template:
    metadata:
      labels:
        app: ecommerce-user-service-mssql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
        - name: ecommerce-user-service-mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          resources:
            requests:
              memory: "2G"
              cpu: "2000m"
            limits:
              memory: "2G"
              cpu: "2000m"
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-user-service
                  key: mssql_password
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: ecommerce-user-service-mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-user-service-mssql
spec:
  selector:
    app: ecommerce-user-service-mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
